spring.application.name=SmartTech

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:smarttech_db}

spring.datasource.username=${PGUSER:postgres}

spring.datasource.password=${PGPASSWORD:12345678910}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=${PORT:8080}