--
-- PostgreSQL database dump
--

-- Dumped from database version 13.20
-- Dumped by pg_dump version 13.20

-- Started on 2026-09-22 16:30:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 207 (class 1259 OID 49187)
-- Name: admin_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.admin_users OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 49185)
-- Name: admin_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 49215)
-- Name: authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authors (
    id bigint NOT NULL,
    name character varying(80) NOT NULL
);


ALTER TABLE public.authors OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 49213)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.authors_id_seq OWNER TO postgres;

--
-- TOC entry 3069 (class 0 OID 0)
-- Dependencies: 210
-- Name: authors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.authors_id_seq OWNED BY public.authors.id;


--
-- TOC entry 201 (class 1259 OID 40996)
-- Name: brands; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brands (
    id bigint NOT NULL,
    name character varying(80) NOT NULL
);


ALTER TABLE public.brands OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 40994)
-- Name: brands_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.brands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.brands_id_seq OWNER TO postgres;

--
-- TOC entry 3070 (class 0 OID 0)
-- Dependencies: 200
-- Name: brands_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.brands_id_seq OWNED BY public.brands.id;


--
-- TOC entry 205 (class 1259 OID 41023)
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    device_id bigint NOT NULL,
    content character varying(1000) NOT NULL,
    rating integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    author_id bigint NOT NULL,
    CONSTRAINT comments_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 41021)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.comments_id_seq OWNER TO postgres;

--
-- TOC entry 3071 (class 0 OID 0)
-- Dependencies: 204
-- Name: comments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.comments_id_seq OWNED BY public.comments.id;


--
-- TOC entry 209 (class 1259 OID 49205)
-- Name: device_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device_types (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.device_types OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 49203)
-- Name: device_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.device_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.device_types_id_seq OWNER TO postgres;

--
-- TOC entry 3072 (class 0 OID 0)
-- Dependencies: 208
-- Name: device_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.device_types_id_seq OWNED BY public.device_types.id;


--
-- TOC entry 203 (class 1259 OID 41006)
-- Name: devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.devices (
    id bigint NOT NULL,
    name character varying(140) NOT NULL,
    brand_id bigint NOT NULL,
    release_date date NOT NULL,
    processor character varying(120) NOT NULL,
    memory character varying(120) NOT NULL,
    storage character varying(120) NOT NULL,
    screen character varying(80) NOT NULL,
    description character varying(1000) NOT NULL,
    image_url character varying(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    type_id bigint NOT NULL,
    CONSTRAINT devices_price_check CHECK ((price >= (0)::numeric))
);


ALTER TABLE public.devices OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 41004)
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.devices_id_seq OWNER TO postgres;

--
-- TOC entry 3073 (class 0 OID 0)
-- Dependencies: 202
-- Name: devices_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.devices_id_seq OWNED BY public.devices.id;


--
-- TOC entry 2890 (class 2604 OID 49218)
-- Name: authors id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors ALTER COLUMN id SET DEFAULT nextval('public.authors_id_seq'::regclass);


--
-- TOC entry 2883 (class 2604 OID 40999)
-- Name: brands id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brands ALTER COLUMN id SET DEFAULT nextval('public.brands_id_seq'::regclass);


--
-- TOC entry 2886 (class 2604 OID 41026)
-- Name: comments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments ALTER COLUMN id SET DEFAULT nextval('public.comments_id_seq'::regclass);


--
-- TOC entry 2889 (class 2604 OID 49208)
-- Name: device_types id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_types ALTER COLUMN id SET DEFAULT nextval('public.device_types_id_seq'::regclass);


--
-- TOC entry 2884 (class 2604 OID 41009)
-- Name: devices id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices ALTER COLUMN id SET DEFAULT nextval('public.devices_id_seq'::regclass);


--
-- TOC entry 3059 (class 0 OID 49187)
-- Dependencies: 207
-- Data for Name: admin_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_users (id, email, enabled, password, username) FROM stdin;
1	admin@smarttech.com	t	$2a$10$gm337NSIscEOjssPvNU1PeKaYPYPfwrSGFBjhGzJ3ZPt8dfKhj14W	admin
\.


--
-- TOC entry 3063 (class 0 OID 49215)
-- Dependencies: 211
-- Data for Name: authors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authors (id, name) FROM stdin;
1	Julian
2	Prueba CRUD
\.


--
-- TOC entry 3053 (class 0 OID 40996)
-- Dependencies: 201
-- Data for Name: brands; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.brands (id, name) FROM stdin;
1	Samsung
2	Apple
3	Lenovo
4	Xiaomi
\.


--
-- TOC entry 3057 (class 0 OID 41023)
-- Dependencies: 205
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comments (id, device_id, content, rating, created_at, author_id) FROM stdin;
1	2	Excelente dispositivo, tiene muy buenas características. Comentario actualizado	5	2026-08-13 18:48:00.753958	1
2	1	El dispositivo presenta buenas características y una propuesta tecnológica interesante.	5	2026-08-19 17:37:21.212309	1
\.


--
-- TOC entry 3061 (class 0 OID 49205)
-- Dependencies: 209
-- Data for Name: device_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.device_types (id, name) FROM stdin;
1	Celular
2	Portátil
\.


--
-- TOC entry 3055 (class 0 OID 41006)
-- Dependencies: 203
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.devices (id, name, brand_id, release_date, processor, memory, storage, screen, description, image_url, price, type_id) FROM stdin;
4	Xiaomi 14	4	2024-02-25	Snapdragon 8 Gen 3	12 GB RAM	512 GB	6.36 pulgadas AMOLED	Dispositivo compacto de gama alta con gran capacidad de almacenamiento y cámara avanzada.	https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80	2799000.00	1
2	iPhone 16	2	2024-09-20	Apple A18	8 GB RAM	128 GB	6.1 pulgadas OLED	Smartphone con enfoque en rendimiento, fotografía computacional y ecosistema Apple.	https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=900&q=80	3999000.00	1
1	Galaxy S25	1	2025-01-22	Snapdragon 8 Elite	12 GB RAM	256 GB	6.2 pulgadas AMOLED	Celular de alto rendimiento orientado a productividad, fotografía y entretenimiento.	https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80	3299000.00	1
3	ThinkPad X1 Carbon	3	2025-01-07	Intel Core Ultra	16 GB RAM	512 GB SSD	14 pulgadas	Portátil empresarial diseñado para productividad, movilidad y trabajo profesional.	https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80	6899000.00	2
\.


--
-- TOC entry 3074 (class 0 OID 0)
-- Dependencies: 206
-- Name: admin_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_users_id_seq', 1, true);


--
-- TOC entry 3075 (class 0 OID 0)
-- Dependencies: 210
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authors_id_seq', 3, true);


--
-- TOC entry 3076 (class 0 OID 0)
-- Dependencies: 200
-- Name: brands_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.brands_id_seq', 6, true);


--
-- TOC entry 3077 (class 0 OID 0)
-- Dependencies: 204
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


--
-- TOC entry 3078 (class 0 OID 0)
-- Dependencies: 208
-- Name: device_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.device_types_id_seq', 3, true);


--
-- TOC entry 3079 (class 0 OID 0)
-- Dependencies: 202
-- Name: devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.devices_id_seq', 8, true);


--
-- TOC entry 2905 (class 2606 OID 49191)
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);


--
-- TOC entry 2915 (class 2606 OID 49222)
-- Name: authors authors_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_name_key UNIQUE (name);


--
-- TOC entry 2917 (class 2606 OID 49220)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 2892 (class 2606 OID 41003)
-- Name: brands brands_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT brands_name_key UNIQUE (name);


--
-- TOC entry 2894 (class 2606 OID 41001)
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);


--
-- TOC entry 2901 (class 2606 OID 41033)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 2911 (class 2606 OID 49212)
-- Name: device_types device_types_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_types
    ADD CONSTRAINT device_types_name_key UNIQUE (name);


--
-- TOC entry 2913 (class 2606 OID 49210)
-- Name: device_types device_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device_types
    ADD CONSTRAINT device_types_pkey PRIMARY KEY (id);


--
-- TOC entry 2896 (class 2606 OID 41015)
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- TOC entry 2907 (class 2606 OID 49202)
-- Name: admin_users uk3fgxk4ewgaxgtgvqwb1jjudj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT uk3fgxk4ewgaxgtgvqwb1jjudj6 UNIQUE (username);


--
-- TOC entry 2909 (class 2606 OID 49197)
-- Name: admin_users ukcp8822350s9vtyww7xdbgeuvu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT ukcp8822350s9vtyww7xdbgeuvu UNIQUE (email);


--
-- TOC entry 2902 (class 1259 OID 49234)
-- Name: idx_comments_author; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_comments_author ON public.comments USING btree (author_id);


--
-- TOC entry 2903 (class 1259 OID 41041)
-- Name: idx_comments_device; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_comments_device ON public.comments USING btree (device_id);


--
-- TOC entry 2897 (class 1259 OID 41039)
-- Name: idx_devices_brand; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_devices_brand ON public.devices USING btree (brand_id);


--
-- TOC entry 2898 (class 1259 OID 41040)
-- Name: idx_devices_release_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_devices_release_date ON public.devices USING btree (release_date DESC);


--
-- TOC entry 2899 (class 1259 OID 49233)
-- Name: idx_devices_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_devices_type ON public.devices USING btree (type_id);


--
-- TOC entry 2920 (class 2606 OID 41034)
-- Name: comments comments_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE;


--
-- TOC entry 2918 (class 2606 OID 41016)
-- Name: devices devices_brand_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brands(id);


--
-- TOC entry 2921 (class 2606 OID 49228)
-- Name: comments fk_comments_author; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES public.authors(id);


--
-- TOC entry 2919 (class 2606 OID 49223)
-- Name: devices fk_devices_device_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT fk_devices_device_type FOREIGN KEY (type_id) REFERENCES public.device_types(id);


-- Completed on 2026-09-22 16:30:56

--
-- PostgreSQL database dump complete
--

